spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/maxgitspot/configData-curso-inetum
          default-label: main
server:
  port: 8888